{"metadata":{"externalID":"s:14SwiftOperators20OperatorErrorHandlera","role":"symbol","modules":[{"name":"SwiftOperators"}],"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"OperatorErrorHandler"}],"symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OperatorErrorHandler"}],"title":"OperatorErrorHandler"},"sections":[],"identifier":{"url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorErrorHandler","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A function that receives an operator precedence error and may do with it","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"whatever it likes."}],"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/swiftoperators\/operatorerrorhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"OperatorErrorHandler","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:14SwiftOperators13OperatorErrorO","text":"OperatorError","kind":"typeIdentifier","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorError"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"Operator precedence error handlers are passed into each function in the","type":"text"},{"text":" ","type":"text"},{"text":"operator-precedence parser that can produce a failure. The handler","type":"text"},{"text":" ","type":"text"},{"text":"may choose to throw (in which case the error will propagate outward) or","type":"text"},{"type":"text","text":" "},{"type":"text","text":"may separately record\/drop the error and return without throwing (in"},{"type":"text","text":" "},{"type":"text","text":"which case the operator-precedence parser will recover)."}],"type":"paragraph"}]}],"references":{"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators/OperatorError":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OperatorError","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes errors that can occur when working with user-defined operators."}],"title":"OperatorError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OperatorError"}],"url":"\/documentation\/swiftoperators\/operatorerror","type":"topic","kind":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators":{"role":"collection","title":"SwiftOperators","kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators","url":"\/documentation\/swiftoperators","abstract":[],"type":"topic"},"doc://com.SwiftyLab.HelperCoders/documentation/SwiftOperators/OperatorErrorHandler":{"abstract":[{"text":"A function that receives an operator precedence error and may do with it","type":"text"},{"type":"text","text":" "},{"type":"text","text":"whatever it likes."}],"type":"topic","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/SwiftOperators\/OperatorErrorHandler","title":"OperatorErrorHandler","navigatorTitle":[{"text":"OperatorErrorHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperatorErrorHandler"}],"url":"\/documentation\/swiftoperators\/operatorerrorhandler"}}}